// Seed data for the granular billing catalog.
// Prices are realistic for an Indian mid-tier private hospital (INR).
// Each entry's `subtype` lives in the matching ServiceXxx table.

const CATALOG = [
  // ── LAB TESTS ──────────────────────────────────────────────────────────────
  { code: 'CBC',         name: 'Complete Blood Count',                  category: 'lab', unitPrice: 350,
    subtype: { table: 'ServiceLab', specimenType: 'blood',  container: 'EDTA',        methodology: 'Automated cell counter',                                    turnaroundHours: 2,  fastingRequired: false } },
  { code: 'BMP',         name: 'Basic Metabolic Panel (Na/K/Cl/Bun/Cr)', category: 'lab', unitPrice: 600,
    subtype: { table: 'ServiceLab', specimenType: 'blood',  container: 'plain',       methodology: 'Spectrophotometry',                                          turnaroundHours: 4,  fastingRequired: false } },
  { code: 'LFT',         name: 'Liver Function Test',                   category: 'lab', unitPrice: 650,
    subtype: { table: 'ServiceLab', specimenType: 'blood',  container: 'plain',       methodology: 'Spectrophotometry',                                          turnaroundHours: 4,  fastingRequired: false } },
  { code: 'KFT',         name: 'Kidney Function Test',                  category: 'lab', unitPrice: 650,
    subtype: { table: 'ServiceLab', specimenType: 'blood',  container: 'plain',       methodology: 'Spectrophotometry',                                          turnaroundHours: 4,  fastingRequired: false } },
  { code: 'HBA1C',       name: 'HbA1c (Glycated Haemoglobin)',          category: 'lab', unitPrice: 500,
    subtype: { table: 'ServiceLab', specimenType: 'blood',  container: 'EDTA',        methodology: 'HPLC',           unitsOfMeasure: '%', normalLow: 4, normalHigh: 5.6, turnaroundHours: 4, fastingRequired: false } },
  { code: 'LIPID',       name: 'Lipid Profile',                         category: 'lab', unitPrice: 700,
    subtype: { table: 'ServiceLab', specimenType: 'blood',  container: 'plain',       methodology: 'Spectrophotometry', unitsOfMeasure: 'mg/dL',                                       turnaroundHours: 6, fastingRequired: true } },
  { code: 'TFT',         name: 'Thyroid Profile (TSH, T3, T4)',         category: 'lab', unitPrice: 800,
    subtype: { table: 'ServiceLab', specimenType: 'blood',  container: 'plain',       methodology: 'Chemiluminescence', turnaroundHours: 6, fastingRequired: false } },
  { code: 'URINE-R',     name: 'Urine Routine and Microscopy',          category: 'lab', unitPrice: 150,
    subtype: { table: 'ServiceLab', specimenType: 'urine', container: 'sterile',     methodology: 'Microscopy + dipstick',                                       turnaroundHours: 2,  fastingRequired: false } },
  { code: 'FBS',         name: 'Fasting Blood Glucose',                 category: 'lab', unitPrice: 100,
    subtype: { table: 'ServiceLab', specimenType: 'blood',  container: 'fluoride',    methodology: 'Glucose oxidase',  unitsOfMeasure: 'mg/dL', normalLow: 70, normalHigh: 110, turnaroundHours: 1, fastingRequired: true } },
  { code: 'TROP-I',      name: 'Troponin I (high sensitivity)',         category: 'lab', unitPrice: 1200,
    subtype: { table: 'ServiceLab', specimenType: 'blood',  container: 'plain',       methodology: 'Chemiluminescence', unitsOfMeasure: 'ng/mL', turnaroundHours: 1, fastingRequired: false } },
  { code: 'DDIMER',      name: 'D-Dimer',                               category: 'lab', unitPrice: 1500,
    subtype: { table: 'ServiceLab', specimenType: 'blood',  container: 'citrate',     methodology: 'Immunoturbidimetry',                                          turnaroundHours: 2, fastingRequired: false } },
  { code: 'CRP',         name: 'C-Reactive Protein',                    category: 'lab', unitPrice: 450,
    subtype: { table: 'ServiceLab', specimenType: 'blood',  container: 'plain',       methodology: 'Immunoturbidimetry',                                          turnaroundHours: 2, fastingRequired: false } },
  { code: 'ABG',         name: 'Arterial Blood Gas Analysis',           category: 'lab', unitPrice: 600,
    subtype: { table: 'ServiceLab', specimenType: 'arterial blood', container: 'heparinised', methodology: 'Blood gas analyser', turnaroundHours: 1, fastingRequired: false } },
  { code: 'COAG',        name: 'Coagulation Profile (PT/INR/aPTT)',     category: 'lab', unitPrice: 650,
    subtype: { table: 'ServiceLab', specimenType: 'blood',  container: 'citrate',     methodology: 'Coagulometer', turnaroundHours: 2, fastingRequired: false } },
  { code: 'BLOOD-CULT',  name: 'Blood Culture (aerobic)',               category: 'lab', unitPrice: 1200,
    subtype: { table: 'ServiceLab', specimenType: 'blood',  container: 'culture bottle', methodology: 'BacT/Alert',  turnaroundHours: 72, fastingRequired: false } },
  { code: 'HIV-RAPID',   name: 'HIV 1 & 2 Rapid Antibody',              category: 'lab', unitPrice: 500,
    subtype: { table: 'ServiceLab', specimenType: 'blood',  container: 'plain',       methodology: 'Immunochromatography', turnaroundHours: 1, fastingRequired: false } },
  { code: 'HBSAG',       name: 'Hepatitis B Surface Antigen',           category: 'lab', unitPrice: 400,
    subtype: { table: 'ServiceLab', specimenType: 'blood',  container: 'plain',       methodology: 'ELISA', turnaroundHours: 4, fastingRequired: false } },
  { code: 'PCT',         name: 'Procalcitonin',                         category: 'lab', unitPrice: 2000,
    subtype: { table: 'ServiceLab', specimenType: 'blood',  container: 'plain',       methodology: 'Chemiluminescence', turnaroundHours: 2, fastingRequired: false } },

  // ── IMAGING ───────────────────────────────────────────────────────────────
  { code: 'XR-CHEST-PA', name: 'Chest X-ray PA view',                   category: 'imaging', unitPrice: 350,
    subtype: { table: 'ServiceImaging', modality: 'xray',       bodyRegion: 'chest',      contrast: 'none', durationMinutes: 5,  radiationDoseMsv: 0.1 } },
  { code: 'XR-ABD',      name: 'Abdominal X-ray (KUB)',                 category: 'imaging', unitPrice: 400,
    subtype: { table: 'ServiceImaging', modality: 'xray',       bodyRegion: 'abdomen',    contrast: 'none', durationMinutes: 5,  radiationDoseMsv: 0.7 } },
  { code: 'USG-ABD',     name: 'Ultrasound Abdomen',                    category: 'imaging', unitPrice: 1200,
    subtype: { table: 'ServiceImaging', modality: 'ultrasound', bodyRegion: 'abdomen',    contrast: 'none', durationMinutes: 20, prepInstructions: 'Fasting 6h preferred' } },
  { code: 'USG-PELV',    name: 'Ultrasound Pelvis (transabdominal)',    category: 'imaging', unitPrice: 1100,
    subtype: { table: 'ServiceImaging', modality: 'ultrasound', bodyRegion: 'pelvis',     contrast: 'none', durationMinutes: 20, prepInstructions: 'Full bladder required' } },
  { code: 'USG-OB',      name: 'Ultrasound Obstetric',                  category: 'imaging', unitPrice: 1500,
    subtype: { table: 'ServiceImaging', modality: 'ultrasound', bodyRegion: 'obstetric',  contrast: 'none', durationMinutes: 25 } },
  { code: 'CT-HEAD-PL',  name: 'CT Head — plain',                       category: 'imaging', unitPrice: 2500,
    subtype: { table: 'ServiceImaging', modality: 'ct',         bodyRegion: 'head',       contrast: 'none', durationMinutes: 10, radiationDoseMsv: 2.0 } },
  { code: 'CT-HEAD-C',   name: 'CT Head — with contrast',               category: 'imaging', unitPrice: 4500,
    subtype: { table: 'ServiceImaging', modality: 'ct',         bodyRegion: 'head',       contrast: 'iv',   durationMinutes: 20, radiationDoseMsv: 2.0, prepInstructions: 'Renal function required' } },
  { code: 'CT-CHEST',    name: 'CT Chest',                              category: 'imaging', unitPrice: 3500,
    subtype: { table: 'ServiceImaging', modality: 'ct',         bodyRegion: 'chest',      contrast: 'iv',   durationMinutes: 15, radiationDoseMsv: 7.0 } },
  { code: 'CT-ABD',      name: 'CT Abdomen and Pelvis',                 category: 'imaging', unitPrice: 4500,
    subtype: { table: 'ServiceImaging', modality: 'ct',         bodyRegion: 'abdomen',    contrast: 'iv',   durationMinutes: 25, radiationDoseMsv: 10.0 } },
  { code: 'MRI-BRAIN',   name: 'MRI Brain',                             category: 'imaging', unitPrice: 6000,
    subtype: { table: 'ServiceImaging', modality: 'mri',        bodyRegion: 'brain',      contrast: 'none', durationMinutes: 45 } },
  { code: 'MRI-SPINE',   name: 'MRI Spine (single segment)',            category: 'imaging', unitPrice: 6500,
    subtype: { table: 'ServiceImaging', modality: 'mri',        bodyRegion: 'spine',      contrast: 'none', durationMinutes: 45 } },
  { code: 'ECG-12',      name: 'ECG 12-lead',                           category: 'imaging', unitPrice: 250,
    subtype: { table: 'ServiceImaging', modality: 'ecg',        bodyRegion: 'cardiac',    contrast: 'none', durationMinutes: 5 } },
  { code: 'ECHO-2D',     name: '2D Echocardiogram with Doppler',        category: 'imaging', unitPrice: 3000,
    subtype: { table: 'ServiceImaging', modality: 'echo',       bodyRegion: 'cardiac',    contrast: 'none', durationMinutes: 30 } },
  { code: 'TMT',         name: 'Treadmill Test',                        category: 'imaging', unitPrice: 2500,
    subtype: { table: 'ServiceImaging', modality: 'tmt',        bodyRegion: 'cardiac',    contrast: 'none', durationMinutes: 30 } },
  { code: 'HOLTER',      name: 'Holter Monitoring (24h)',               category: 'imaging', unitPrice: 3500,
    subtype: { table: 'ServiceImaging', modality: 'holter',     bodyRegion: 'cardiac',    contrast: 'none', durationMinutes: 1440 } },

  // ── PROCEDURES ────────────────────────────────────────────────────────────
  { code: 'APPEND-LAP',  name: 'Laparoscopic Appendectomy',             category: 'procedure', unitPrice: 45000,
    subtype: { table: 'ServiceProcedure', anaesthesiaType: 'general', otRequired: true,  durationMinutes: 60,  postOpStayDays: 2, specialty: 'general_surgery', surgeonGrade: 'consultant' } },
  { code: 'CHOLE-LAP',   name: 'Laparoscopic Cholecystectomy',          category: 'procedure', unitPrice: 55000,
    subtype: { table: 'ServiceProcedure', anaesthesiaType: 'general', otRequired: true,  durationMinutes: 90,  postOpStayDays: 2, specialty: 'general_surgery', surgeonGrade: 'consultant' } },
  { code: 'HERNIA-MESH', name: 'Inguinal Hernia Repair (mesh)',         category: 'procedure', unitPrice: 38000,
    subtype: { table: 'ServiceProcedure', anaesthesiaType: 'spinal',  otRequired: true,  durationMinutes: 60,  postOpStayDays: 1, specialty: 'general_surgery', surgeonGrade: 'consultant' } },
  { code: 'CSECTION',    name: 'Caesarean Section',                     category: 'procedure', unitPrice: 50000,
    subtype: { table: 'ServiceProcedure', anaesthesiaType: 'spinal',  otRequired: true,  durationMinutes: 45,  postOpStayDays: 3, specialty: 'ob_gyn',           surgeonGrade: 'consultant' } },
  { code: 'DELIV-NORM',  name: 'Normal Vaginal Delivery',               category: 'procedure', unitPrice: 25000,
    subtype: { table: 'ServiceProcedure', anaesthesiaType: 'none',    otRequired: false, durationMinutes: 90,  postOpStayDays: 2, specialty: 'ob_gyn',           surgeonGrade: 'consultant' } },
  { code: 'DIALYSIS-HD', name: 'Haemodialysis (per session)',           category: 'procedure', unitPrice: 2500,
    subtype: { table: 'ServiceProcedure', anaesthesiaType: 'none',    otRequired: false, durationMinutes: 240,                  specialty: 'nephrology' } },
  { code: 'LP',          name: 'Lumbar Puncture',                       category: 'procedure', unitPrice: 3500,
    subtype: { table: 'ServiceProcedure', anaesthesiaType: 'local',   otRequired: false, durationMinutes: 30,                   specialty: 'neurology' } },
  { code: 'CVL',         name: 'Central Venous Line Insertion',         category: 'procedure', unitPrice: 2500,
    subtype: { table: 'ServiceProcedure', anaesthesiaType: 'local',   otRequired: false, durationMinutes: 30,                   specialty: 'critical_care' } },
  { code: 'IV-CANN',     name: 'IV Cannulation (peripheral)',           category: 'procedure', unitPrice: 150,
    subtype: { table: 'ServiceProcedure', anaesthesiaType: 'none',    otRequired: false, durationMinutes: 5 } },
  { code: 'FOLEY',       name: 'Foley Catheter Insertion',              category: 'procedure', unitPrice: 500,
    subtype: { table: 'ServiceProcedure', anaesthesiaType: 'local',   otRequired: false, durationMinutes: 10 } },
  { code: 'EGD',         name: 'Upper GI Endoscopy',                    category: 'procedure', unitPrice: 4500,
    subtype: { table: 'ServiceProcedure', anaesthesiaType: 'sedation', otRequired: false, durationMinutes: 20,                  specialty: 'gastroenterology' } },
  { code: 'COLONO',      name: 'Colonoscopy',                           category: 'procedure', unitPrice: 6500,
    subtype: { table: 'ServiceProcedure', anaesthesiaType: 'sedation', otRequired: false, durationMinutes: 40,                  specialty: 'gastroenterology' } },
  { code: 'SUTURE',      name: 'Suturing — minor wound',                category: 'procedure', unitPrice: 1500,
    subtype: { table: 'ServiceProcedure', anaesthesiaType: 'local',   otRequired: false, durationMinutes: 15 } },
  { code: 'DRESSING',    name: 'Wound Dressing',                        category: 'procedure', unitPrice: 300,
    subtype: { table: 'ServiceProcedure', anaesthesiaType: 'none',    otRequired: false, durationMinutes: 10 } },

  // ── CONSUMABLES (medical supplies) ─────────────────────────────────────────
  { code: 'CANN-18G',    name: 'IV Cannula 18G',                        category: 'misc', unitPrice: 35,
    subtype: { table: 'ServiceConsumable', sku: 'CANN18',   size: '18G',     sterile: true,  singleUse: true,  unit: 'piece' } },
  { code: 'CANN-20G',    name: 'IV Cannula 20G',                        category: 'misc', unitPrice: 35,
    subtype: { table: 'ServiceConsumable', sku: 'CANN20',   size: '20G',     sterile: true,  singleUse: true,  unit: 'piece' } },
  { code: 'CANN-22G',    name: 'IV Cannula 22G',                        category: 'misc', unitPrice: 40,
    subtype: { table: 'ServiceConsumable', sku: 'CANN22',   size: '22G',     sterile: true,  singleUse: true,  unit: 'piece' } },
  { code: 'IV-SET',      name: 'IV Set (drip set)',                     category: 'misc', unitPrice: 45,
    subtype: { table: 'ServiceConsumable', sku: 'IVSET',    sterile: true,  singleUse: true,  unit: 'piece' } },
  { code: '3WAY',        name: 'Three-way Stopcock',                    category: 'misc', unitPrice: 15,
    subtype: { table: 'ServiceConsumable', sku: '3WAY',     sterile: true,  singleUse: true,  unit: 'piece' } },
  { code: 'SYR-2',       name: 'Syringe 2 mL',                          category: 'misc', unitPrice: 4,
    subtype: { table: 'ServiceConsumable', sku: 'SYR2',     size: '2mL',     sterile: true,  singleUse: true,  unit: 'piece' } },
  { code: 'SYR-5',       name: 'Syringe 5 mL',                          category: 'misc', unitPrice: 6,
    subtype: { table: 'ServiceConsumable', sku: 'SYR5',     size: '5mL',     sterile: true,  singleUse: true,  unit: 'piece' } },
  { code: 'SYR-10',      name: 'Syringe 10 mL',                         category: 'misc', unitPrice: 10,
    subtype: { table: 'ServiceConsumable', sku: 'SYR10',    size: '10mL',    sterile: true,  singleUse: true,  unit: 'piece' } },
  { code: 'SYR-50',      name: 'Syringe 50 mL',                         category: 'misc', unitPrice: 40,
    subtype: { table: 'ServiceConsumable', sku: 'SYR50',    size: '50mL',    sterile: true,  singleUse: true,  unit: 'piece' } },
  { code: 'GAUZE-4',     name: 'Gauze pad 4x4 cm',                      category: 'misc', unitPrice: 8,
    subtype: { table: 'ServiceConsumable', sku: 'GAUZE4',   size: '4x4cm',   sterile: true,  singleUse: true,  unit: 'piece' } },
  { code: 'GLOVES-SURG', name: 'Surgical Gloves (sterile pair)',        category: 'misc', unitPrice: 15,
    subtype: { table: 'ServiceConsumable', sku: 'GLSURG',   sterile: true,  singleUse: true,  unit: 'pair' } },
  { code: 'GLOVES-EXAM', name: 'Examination Gloves (non-sterile)',      category: 'misc', unitPrice: 4,
    subtype: { table: 'ServiceConsumable', sku: 'GLEXAM',   sterile: false, singleUse: true,  unit: 'pair' } },
  { code: 'FOLEY-14F',   name: 'Foley Catheter 14F',                    category: 'misc', unitPrice: 120,
    subtype: { table: 'ServiceConsumable', sku: 'FOLEY14',  size: '14F',     sterile: true,  singleUse: true,  unit: 'piece' } },
  { code: 'FOLEY-16F',   name: 'Foley Catheter 16F',                    category: 'misc', unitPrice: 120,
    subtype: { table: 'ServiceConsumable', sku: 'FOLEY16',  size: '16F',     sterile: true,  singleUse: true,  unit: 'piece' } },
  { code: 'URO-BAG',     name: 'Urine Collection Bag (2L)',             category: 'misc', unitPrice: 65,
    subtype: { table: 'ServiceConsumable', sku: 'UROBAG',   size: '2L',      sterile: true,  singleUse: true,  unit: 'piece' } },
  { code: 'SUTURE-SET',  name: 'Suture Set (basic)',                    category: 'misc', unitPrice: 250,
    subtype: { table: 'ServiceConsumable', sku: 'SUTKIT',   sterile: true,  singleUse: true,  unit: 'set' } },
  { code: 'DRAPE',       name: 'Surgical Drape',                        category: 'misc', unitPrice: 200,
    subtype: { table: 'ServiceConsumable', sku: 'DRAPE',    sterile: true,  singleUse: true,  unit: 'piece' } },
  { code: 'N95',         name: 'N95 Respirator Mask',                   category: 'misc', unitPrice: 40,
    subtype: { table: 'ServiceConsumable', sku: 'N95',      sterile: false, singleUse: true,  unit: 'piece' } },
  { code: 'MASK-3PLY',   name: '3-ply Surgical Mask',                   category: 'misc', unitPrice: 3,
    subtype: { table: 'ServiceConsumable', sku: '3PLY',     sterile: false, singleUse: true,  unit: 'piece' } },
];

module.exports = CATALOG;
