export const queryKeys = {
  patients: (viewMode: string) => ['patients', viewMode] as const,
  patientDetail: (id: string | undefined) => ['patient', id] as const,
  patientTasks: (id: string | undefined) => ['patient', id, 'tasks'] as const,
  tasksMy: (role: string | undefined, limit = 50) => ['tasks', 'my', { role: role || 'unknown', limit }] as const,
  escalations: () => ['escalations'] as const,
  statistics: {
    summary: (period: string, filters: Record<string, string>) => ['statistics', 'summary', period, filters] as const,
    diseases: (period: string, filters: Record<string, string>) => ['statistics', 'diseases', period, filters] as const,
    demographics: (period: string, filters: Record<string, string>) => ['statistics', 'demographics', period, filters] as const,
    medications: (period: string, filters: Record<string, string>) => ['statistics', 'medications', period, filters] as const,
    admissions: (period: string, filters: Record<string, string>) => ['statistics', 'admissions', period, filters] as const,
    outcomes: (period: string, filters: Record<string, string>) => ['statistics', 'outcomes', period, filters] as const,
  },
  clinical: {
    medicalHistory: (patientId: string | undefined) => ['clinical', patientId, 'medicalHistory'] as const,
    structuredAllergies: (patientId: string | undefined) => ['clinical', patientId, 'structuredAllergies'] as const,
    clinicalPresentation: (patientId: string | undefined) => ['clinical', patientId, 'clinicalPresentation'] as const,
    labInvestigations: (patientId: string | undefined) => ['clinical', patientId, 'labInvestigations'] as const,
    imagingReports: (patientId: string | undefined) => ['clinical', patientId, 'imagingReports'] as const,
    clinicalProcedures: (patientId: string | undefined) => ['clinical', patientId, 'clinicalProcedures'] as const,
    clinicalTeam: (patientId: string | undefined) => ['clinical', patientId, 'clinicalTeam'] as const,
    toxicology: (patientId: string | undefined) => ['clinical', patientId, 'toxicology'] as const,
  },
};
